const rawChannels = [
  // --- BANGLA ---
  { group: "Bangla", name: "ATN BANGLA", stream: "/player.php?stream=80&autoplay=1", logo: "/assets/images/ATN BANGLA1745044183.png" },
  { group: "Bangla", name: "ATN NEWS", stream: "/player.php?stream=95&autoplay=1", logo: "/assets/images/ATN NEWS1745045113.png" },
  { group: "Bangla", name: "CHANNEL 24", stream: "/player.php?stream=82&autoplay=1", logo: "/assets/images/CHANNEL 241745044263.png" },
  { group: "Bangla", name: "CHANNEL I", stream: "/player.php?stream=81&autoplay=1", logo: "/assets/images/CHANNEL I1745044237.png" },
  { group: "Bangla", name: "COLORS BANGLA CINEMA", stream: "/player.php?stream=47&autoplay=1", logo: "/assets/images/COLORS BANGLA CINEMA1745041486.png" },
  { group: "Bangla", name: "COLORS BANGLA HD", stream: "/player.php?stream=12&autoplay=1", logo: "/assets/images/COLORS BANGLA HD1745033576.png" },
  { group: "Bangla", name: "GTV", stream: "/player.php?stream=56&autoplay=1", logo: "/assets/images/GTV1745042853.png" },
  { group: "Bangla", name: "INDEPENDENT TV", stream: "/player.php?stream=77&autoplay=1", logo: "/assets/images/INDEPENDENT TV1745044077.png" },
  { group: "Bangla", name: "JALSHA MOVIES HD", stream: "/player.php?stream=19&autoplay=1", logo: "/assets/images/JALSHA MOVIES HD1745034005.png" },
  { group: "Bangla", name: "JAMUNA TV", stream: "/player.php?stream=76&autoplay=1", logo: "/assets/images/JAMUNA TV1745044052.png" },
  { group: "Bangla", name: "MAASRANGA HD", stream: "/player.php?stream=78&autoplay=1", logo: "/assets/images/MAASRANGA HD1745044117.png" },
  { group: "Bangla", name: "NAGORIK", stream: "/player.php?stream=54&autoplay=1", logo: "/assets/images/NAGORIK1745042776.png" },
  { group: "Bangla", name: "SOMOY TV", stream: "/player.php?stream=79&autoplay=1", logo: "/assets/images/SOMOY TV1745044149.png" },
  { group: "Bangla", name: "SONY AAT", stream: "/player.php?stream=44&autoplay=1", logo: "/assets/images/SONY AAT1745041124.png" },
  { group: "Bangla", name: "STAR JALSHA HD", stream: "/player.php?stream=18&autoplay=1", logo: "/assets/images/STAR JALSHA HD1745033819.png" },
  { group: "Bangla", name: "SUN BANGLA HD", stream: "/player.php?stream=17&autoplay=1", logo: "/assets/images/SUN BANGLA HD1745033791.png" },
  { group: "Bangla", name: "ZEE BANGLA CINEMA", stream: "/player.php?stream=43&autoplay=1", logo: "/assets/images/ZEE BANGLA CINEMA1745040996.png" },
  { group: "Bangla", name: "ZEE BANGLA HD", stream: "/player.php?stream=14&autoplay=1", logo: "/assets/images/ZEE BANGLA HD1745033633.png" },

  // --- SPORTS ---
  { group: "Sports", name: "A SPORTS HD", stream: "/player.php?stream=88&autoplay=1", logo: "/assets/images/A SPORTS HD1745044782.png" },
  { group: "Sports", name: "EUROSPORTS HD", stream: "/player.php?stream=40&autoplay=1", logo: "/assets/images/EUROSPORTS HD1745040406.png" },
  { group: "Sports", name: "FAST SPORTS HD", stream: "/player.php?stream=87&autoplay=1", logo: "/assets/images/FAST SPORTS HD1745044750.png" },
  { group: "Sports", name: "GOLF SPORTS", stream: "/player.php?stream=66&autoplay=1", logo: "/assets/images/GOLF SPORTS1745043338.png" },
  { group: "Sports", name: "PTV SPORTS HD", stream: "/player.php?stream=92&autoplay=1", logo: "/assets/images/PTV SPORTS HD1745044993.png" },
  { group: "Sports", name: "SONY SPORTS 1 HD", stream: "/player.php?stream=74&autoplay=1", logo: "/assets/images/sony sports 1 hd.png" },
  { group: "Sports", name: "SONY SPORTS 2 HD", stream: "/player.php?stream=29&autoplay=1", logo: "/assets/images/sony sports 2 hd.png" },
  { group: "Sports", name: "SONY SPORTS 3", stream: "/player.php?stream=30&autoplay=1", logo: "/assets/images/Sony sports 3.png" },
  { group: "Sports", name: "SONY SPORTS 4", stream: "/player.php?stream=72&autoplay=1", logo: "/assets/images/sony sports 4.png" },
  { group: "Sports", name: "SONY SPORTS 5 HD", stream: "/player.php?stream=101&autoplay=1", logo: "/assets/images/sony sports 5 hd.png" },
  { group: "Sports", name: "SSC SPORTS", stream: "/player.php?stream=96&autoplay=1", logo: "/assets/images/ssc 1 hd.png" },
  { group: "Sports", name: "SSC SPORTS 5 HD", stream: "/player.php?stream=103&autoplay=1", logo: "/assets/images/ssc 5 hd.png" },
  { group: "Sports", name: "STAR SELECT 1 HD", stream: "/player.php?stream=28&autoplay=1", logo: "/assets/images/STAR SELECT 1 HD1745038777.png" },
  { group: "Sports", name: "STAR SPORTS 1 HD", stream: "/player.php?stream=2&autoplay=1", logo: "/assets/images/STAR SPORTS 1 HD1744991778.png" },
  { group: "Sports", name: "STAR SPORTS 2 HD", stream: "/player.php?stream=3&autoplay=1", logo: "/assets/images/STAR SPORTS 2 HD1744991842.png" },
  { group: "Sports", name: "STAR SPORTS 3", stream: "/player.php?stream=31&autoplay=1", logo: "/assets/images/STAR SPORTS 31745039893.png" },
  { group: "Sports", name: "STAR SPORTS SELECT 2 HD", stream: "/player.php?stream=16&autoplay=1", logo: "/assets/images/STAR SPORTS SELECT 2 HD1745033722.png" },
  { group: "Sports", name: "T SPORTS", stream: "/player.php?stream=1&autoplay=1", logo: "/assets/images/T SPORTS1744972630.png" },

    // --- KIDS ---
  { group: "Kids", name: "BAL BHARAT", stream: "/player.php?stream=50&autoplay=1", logo: "/assets/images/BAL BHARAT1745041576.png" },
  { group: "Kids", name: "CARTOON NETWORK", stream: "/player.php?stream=8&autoplay=1", logo: "/assets/images/CARTOON NETWORK1745033414.png" },
  { group: "Kids", name: "DURANTA TV", stream: "/player.php?stream=68&autoplay=1", logo: "/assets/images/DURANTA TV1745043400.png" },
  { group: "Kids", name: "HUNGAMA", stream: "/player.php?stream=49&autoplay=1", logo: "/assets/images/HUNGAMA1745041551.png" },
  { group: "Kids", name: "NICK", stream: "/player.php?stream=46&autoplay=1", logo: "/assets/images/NICK1745041451.png" },
  { group: "Kids", name: "NICK JR", stream: "/player.php?stream=51&autoplay=1", logo: "/assets/images/NICK JR1745042397.png" },
  { group: "Kids", name: "POGO", stream: "/player.php?stream=48&autoplay=1", logo: "/assets/images/POGO1745041515.png" },
  { group: "Kids", name: "SONIC", stream: "/player.php?stream=45&autoplay=1", logo: "/assets/images/SONIC1745041154.png" },
  { group: "Kids", name: "SONY YAY BANGLA", stream: "https://tv.roarzone.info/player.php?stream=toffee/sonyyay", logo: "/assets/images/SONY YAY1745045046.png" },
  { group: "Kids", name: "SONY YAY HINDI", stream: "/player.php?stream=93&autoplay=1", logo: "/assets/images/SONY YAY1745045046.png" },
  { group: "Kids", name: "SUPER HUNGAMA", stream: "/player.php?stream=75&autoplay=1", logo: "/assets/images/SUPER HUNGAMA1745044022.png" },

  // --- HINDI ---
  { group: "Hindi", name: "AND PICTURS HD", stream: "/player.php?stream=5&autoplay=1", logo: "/assets/images/AND PICTURS HD1745031440.png" },
  { group: "Hindi", name: "COLORS CINEPLEX HD", stream: "/player.php?stream=10&autoplay=1", logo: "/assets/images/COLORS CINEPLEX HD1745033519.png" },
  { group: "Hindi", name: "COLORS HD", stream: "/player.php?stream=4&autoplay=1", logo: "/assets/images/COLORS HD1745031404.png" },
  { group: "Hindi", name: "GEO NEWS HD", stream: "/player.php?stream=90&autoplay=1", logo: "/assets/images/GEO NEWS HD1745044892.png" },
  { group: "Hindi", name: "HUM TV", stream: "/player.php?stream=89&autoplay=1", logo: "/assets/images/HUM TV1745044837.png" },
  { group: "Hindi", name: "SONY ENT HD", stream: "/player.php?stream=11&autoplay=1", logo: "/assets/images/SONY ENT HD1745033553.png" },
  { group: "Hindi", name: "SONY MAX HD", stream: "/player.php?stream=21&autoplay=1", logo: "/assets/images/SONY MAX HD1745034069.png" },
  { group: "Hindi", name: "STAR BHARAT HD", stream: "/player.php?stream=100&autoplay=1", logo: "/assets/images/STAR BHARAT HD1745045255.png" },
  { group: "Hindi", name: "STAR GOLD 2 HD", stream: "/player.php?stream=69&autoplay=1", logo: "/assets/images/STAR GOLD 2 HD1745043441.png" },
  { group: "Hindi", name: "STAR GOLD HD", stream: "/player.php?stream=20&autoplay=1", logo: "/assets/images/STAR GOLD HD1745034037.png" },
  { group: "Hindi", name: "STAR GOLD SELECT HD", stream: "/player.php?stream=71&autoplay=1", logo: "/assets/images/STAR GOLD SELECT HD1745043508.png" },
  { group: "Hindi", name: "STAR PLUS HD", stream: "/player.php?stream=24&autoplay=1", logo: "/assets/images/STAR PLUS HD1745038577.png" },
  { group: "Hindi", name: "ZEE CINEMA HD", stream: "/player.php?stream=13&autoplay=1", logo: "/assets/images/ZEE CINEMA HD1745033602.png" },
  { group: "Hindi", name: "ZEE TV HD", stream: "/player.php?stream=7&autoplay=1", logo: "/assets/images/ZEE TV HD1745033383.png" },
  { group: "Hindi", name: "ZING", stream: "/player.php?stream=53&autoplay=1", logo: "/assets/images/ZING1745042718.png" },
  { group: "Hindi", name: "ZOOM", stream: "/player.php?stream=42&autoplay=1", logo: "/assets/images/ZOOM1745040961.png" },

  // --- ENGLISH ---
  { group: "English", name: "ALJAZEETA HD", stream: "/player.php?stream=85&autoplay=1", logo: "/assets/images/ALJAZEETA HD1745044358.png" },
  { group: "English", name: "AND FLIX HD", stream: "/player.php?stream=35&autoplay=1", logo: "/assets/images/AND FLIX HD1745040018.png" },
  { group: "English", name: "AND PRIVE HD", stream: "/player.php?stream=41&autoplay=1", logo: "/assets/images/AND PRIVE HD1745040451.png" },
  { group: "English", name: "AND XPLORE", stream: "/player.php?stream=61&autoplay=1", logo: "/assets/images/AND XPLORE1745043080.png" },
  { group: "English", name: "AXN HD", stream: "/player.php?stream=97&autoplay=1", logo: "/assets/images/AXN HD1745045171.png" },
  { group: "English", name: "HITZ MUSIC", stream: "/player.php?stream=70&autoplay=1", logo: "/assets/images/HITZ MUSIC1745043478.png" },
  { group: "English", name: "LOTUS TV", stream: "/player.php?stream=91&autoplay=1", logo: "/assets/images/LOTUS TV1745044960.png" },
  { group: "English", name: "MN PLUS", stream: "/player.php?stream=36&autoplay=1", logo: "/assets/images/MN PLUS1745040057.png" },
  { group: "English", name: "MNX HD", stream: "/player.php?stream=33&autoplay=1", logo: "/assets/images/MNX HD1745039955.png" },
  { group: "English", name: "MOVIES NOW HD", stream: "/player.php?stream=39&autoplay=1", logo: "/assets/images/MOVIES NOW HD1745040368.png" },
  { group: "English", name: "ROMEDY NOW", stream: "/player.php?stream=34&autoplay=1", logo: "/assets/images/ROMEDY NOW1745039988.png" },
  { group: "English", name: "SONY PIX HD", stream: "/player.php?stream=32&autoplay=1", logo: "/assets/images/SONY PIX HD1745039925.png" },
  { group: "English", name: "STAR MOVIES HD", stream: "/player.php?stream=38&autoplay=1", logo: "/assets/images/STAR MOVIES HD1745040174.png" },
  { group: "English", name: "STAR MOVIES SELECT HD", stream: "/player.php?stream=27&autoplay=1", logo: "/assets/images/STAR MOVIES SELECT HD1745038723.png" },
  { group: "English", name: "ZEE CAFE HD", stream: "/player.php?stream=37&autoplay=1", logo: "/assets/images/ZEE CAFE HD1745040102.png" },

  // --- DOCUMENTARY ---
  { group: "Documentary", name: "ANIMAL PLANET HD", stream: "/player.php?stream=26&autoplay=1", logo: "/assets/images/ANIMAL PLANET HD1745038671.png" },
  { group: "Documentary", name: "BBC EARTH HD", stream: "/player.php?stream=102&autoplay=1", logo: "/assets/images/BBC EARTH HD1745150455.png" },
  { group: "Documentary", name: "DISCOVERY HD", stream: "/player.php?stream=22&autoplay=1", logo: "/assets/images/discovery hd.png" },
  { group: "Documentary", name: "HISTORY TV HD", stream: "/player.php?stream=15&autoplay=1", logo: "/assets/images/HISTORY TV HD1745033679.png" },
  { group: "Documentary", name: "LOVE NATURE", stream: "/player.php?stream=67&autoplay=1", logo: "/assets/images/LOVE NATURE1745043370.png" },
  { group: "Documentary", name: "NATGEO HD", stream: "/player.php?stream=25&autoplay=1", logo: "/assets/images/NATGEO HD1745038634.png" },
  { group: "Documentary", name: "NATGEO WILD HD", stream: "/player.php?stream=23&autoplay=1", logo: "/assets/images/NATGEO WILD HD1745038542.png" },
  { group: "Documentary", name: "SONY BBC EARTH HD", stream: "/player.php?stream=6&autoplay=1", logo: "/assets/images/SONY BBC EARTH HD1745031522.png" },
  { group: "Documentary", name: "TLC HD", stream: "/player.php?stream=9&autoplay=1", logo: "/assets/images/TLC HD1745033484.png" },
  { group: "Documentary", name: "TRAVEL XP", stream: "/player.php?stream=62&autoplay=1", logo: "/assets/images/TRAVEL XP1745043118.png" },

  // --- ISLAMIC ---
  { group: "Islamic", name: "MADANI TV HD", stream: "/player.php?stream=83&autoplay=1", logo: "/assets/images/MADANI TV HD1745044303.png" },
  { group: "Islamic", name: "PEACE TV BANGLA", stream: "/player.php?stream=86&autoplay=1", logo: "/assets/images/PEACE TV BANGLA1745044480.png" }
];

