const rawChannels = [
  // --- BANGLA ---
  { group: "Bangla", name: "Star Jalsha", stream: "https://tv.roarzone.info/player.php?stream=bk/30", logo: "https://tvassets.roarzone.info/images/30.png" },
  { group: "Bangla", name: "Star Jalsha Movies", stream: "https://tv.roarzone.info/player.php?stream=bk/31", logo: "https://tvassets.roarzone.info/images/31.png" },
  { group: "Bangla", name: "Zee Bangla", stream: "https://tv.roarzone.info/player.php?stream=bk/34", logo: "https://tvassets.roarzone.info/images/34.png" },
  { group: "Bangla", name: "ZEE Bangla Cinema", stream: "https://tv.roarzone.info/player.php?stream=bk/29", logo: "https://tvassets.roarzone.info/images/29.png" },
  { group: "Bangla", name: "Colors Bangla", stream: "https://tv.roarzone.info/player.php?stream=bk/66", logo: "https://tvassets.roarzone.info/images/66.png" },
  { group: "Bangla", name: "Sony Aath", stream: "https://tv.roarzone.info/player.php?stream=bk/33", logo: "https://tvassets.roarzone.info/images/33.png" },
  { group: "Bangla", name: "Jamuna TV", stream: "https://tv.roarzone.info/player.php?stream=edge2/jamunatv", logo: "https://tvassets.roarzone.info/images/13.png" },
  { group: "Bangla", name: "Nagorik TV", stream: "https://tv.roarzone.info/player.php?stream=edge2/nagorik", logo: "https://tvassets.roarzone.info/images/59.png" },
  { group: "Bangla", name: "Channel 24", stream: "https://tv.roarzone.info/player.php?stream=edge2/channel24", logo: "https://tvassets.roarzone.info/images/5.png" },
  { group: "Bangla", name: "Somoy TV", stream: "https://tv.roarzone.info/player.php?stream=edge2/somoy", logo: "https://tvassets.roarzone.info/images/17.png" },
  { group: "Bangla", name: "Ekushy TV", stream: "https://tv.roarzone.info/player.php?stream=bk/65", logo: "https://tvassets.roarzone.info/images/65.png" },
  { group: "Bangla", name: "Asian TV", stream: "https://tv.roarzone.info/player.php?stream=edge/asian-tv", logo: "https://tvassets.roarzone.info/images/62.png" },
  { group: "Bangla", name: "ATN Bangla", stream: "https://tv.roarzone.info/player.php?stream=bk/2", logo: "https://tvassets.roarzone.info/images/2.png" },
  { group: "Bangla", name: "ATN NEWS", stream: "https://tv.roarzone.info/player.php?stream=bk/49", logo: "https://tvassets.roarzone.info/images/49.png" },
  { group: "Bangla", name: "Banglavision TV", stream: "https://tv.roarzone.info/player.php?stream=bk/3", logo: "https://tvassets.roarzone.info/images/3.png" },
  { group: "Bangla", name: "Bangla TV", stream: "https://tv.roarzone.info/player.php?stream=bk/19", logo: "https://tvassets.roarzone.info/images/19.png" },
  { group: "Bangla", name: "Boishakhi TV", stream: "https://tv.roarzone.info/player.php?stream=bk/61", logo: "https://tvassets.roarzone.info/images/61.png" },
  { group: "Bangla", name: "BTV", stream: "https://tv.roarzone.info/player.php?stream=bk/53", logo: "https://tvassets.roarzone.info/images/53.png" },
  { group: "Bangla", name: "BTV World", stream: "https://tv.roarzone.info/player.php?stream=bk/84", logo: "https://tvassets.roarzone.info/images/84.png" },
  { group: "Bangla", name: "Channel 9", stream: "https://tv.roarzone.info/player.php?stream=bk/4", logo: "https://tvassets.roarzone.info/images/4.png" },
  { group: "Bangla", name: "Channel I", stream: "https://tv.roarzone.info/player.php?stream=bk/6", logo: "https://tvassets.roarzone.info/images/6.png" },
  { group: "Bangla", name: "DBC News", stream: "https://tv.roarzone.info/player.php?stream=bk/7", logo: "https://tvassets.roarzone.info/images/7.png" },
  { group: "Bangla", name: "Ekattor TV", stream: "https://tv.roarzone.info/player.php?stream=bk/11", logo: "https://tvassets.roarzone.info/images/11.png" },
  { group: "Bangla", name: "Deepto TV", stream: "https://tv.roarzone.info/player.php?stream=bk/8", logo: "https://tvassets.roarzone.info/images/8.png" },
  { group: "Bangla", name: "Desh TV", stream: "https://tv.roarzone.info/player.php?stream=bk/9", logo: "https://tvassets.roarzone.info/images/9.png" },
  { group: "Bangla", name: "Duronto TV", stream: "https://tv.roarzone.info/player.php?stream=bk/10", logo: "https://tvassets.roarzone.info/images/10.png" },
  { group: "Bangla", name: "Independent TV", stream: "https://tv.roarzone.info/player.php?stream=bk/12", logo: "https://tvassets.roarzone.info/images/12.png" },
  { group: "Bangla", name: "Maasranga", stream: "https://tv.roarzone.info/player.php?stream=bk/51", logo: "https://tvassets.roarzone.info/images/51.png" },
  { group: "Bangla", name: "Mohona TV", stream: "https://tv.roarzone.info/player.php?stream=bk/50", logo: "https://tvassets.roarzone.info/images/50.png" },
  { group: "Bangla", name: "Movie Bangla TV", stream: "https://tv.roarzone.info/player.php?stream=bk/86", logo: "https://tvassets.roarzone.info/images/86.png" },
  { group: "Bangla", name: "MY TV", stream: "https://tv.roarzone.info/player.php?stream=bk/56", logo: "https://tvassets.roarzone.info/images/56.png" },
  { group: "Bangla", name: "News24", stream: "https://tv.roarzone.info/player.php?stream=bk/18", logo: "https://tvassets.roarzone.info/images/18.png" },
  { group: "Bangla", name: "NTV", stream: "https://tv.roarzone.info/player.php?stream=bk/54", logo: "https://tvassets.roarzone.info/images/54.png" },
  { group: "Bangla", name: "RTV", stream: "https://tv.roarzone.info/player.php?stream=bk/14", logo: "https://tvassets.roarzone.info/images/14.png" },
  { group: "Bangla", name: "SA TV", stream: "https://tv.roarzone.info/player.php?stream=bk/15", logo: "https://tvassets.roarzone.info/images/15.png" },
  { group: "Bangla", name: "Sangsad TV", stream: "https://tv.roarzone.info/player.php?stream=bk/88", logo: "https://tvassets.roarzone.info/images/88.png" },
  { group: "Bangla", name: "ekhon", stream: "https://tv.roarzone.info/player.php?stream=edge2/ekhontv", logo: "https://tvassets.roarzone.info/images/ekhon-tv.jpg" },
  { group: "Bangla", name: "bijoy-tv", stream: "https://tv.roarzone.info/player.php?stream=ext/bijoy-tv", logo: "https://tvassets.roarzone.info/images/bijoy-tv.jpg" },

  // --- KIDS ---
  { group: "Kids", name: "Cartoon Network", stream: "https://tv.roarzone.info/player.php?stream=bk/79", logo: "https://tvassets.roarzone.info/images/79.png" },
  { group: "Kids", name: "Nick", stream: "https://tv.roarzone.info/player.php?stream=bk/55", logo: "https://tvassets.roarzone.info/images/55.png" },
  { group: "Kids", name: "POGO", stream: "https://tv.roarzone.info/player.php?stream=toffee/pogo_sd", logo: "https://tvassets.roarzone.info/images/pogo.png" },
  { group: "Kids", name: "Discovery Kids", stream: "https://tv.roarzone.info/player.php?stream=toffee/discovery_kids", logo: "https://tvassets.roarzone.info/images/discoverykids.png" },
  { group: "Kids", name: "Sony Yay", stream: "https://tv.roarzone.info/player.php?stream=toffee/sonyyay", logo: "https://tvassets.roarzone.info/images/sonyyay.png" },
  
  // --- SPORTS ---
  { group: "Sports", name: "T Sports", stream: "https://tv.roarzone.info/player.php?stream=edge2/tsports", logo: "https://tvassets.roarzone.info/images/102.png" },
  { group: "Sports", name: "Star Sports 1", stream: "https://tv.roarzone.info/player.php?stream=edge2/star-sports-1-hd", logo: "https://tvassets.roarzone.info/images/25.png" },
  { group: "Sports", name: "Star Sports 2", stream: "https://tv.roarzone.info/player.php?stream=edge2/star-sports-2-hd", logo: "https://tvassets.roarzone.info/images/26.png" },
  { group: "Sports", name: "Gazi TV", stream: "https://tv.roarzone.info/player.php?stream=edge2/gazitv", logo: "https://tvassets.roarzone.info/images/1.png" },
  { group: "Sports", name: "PTV spotrs", stream: "https://tv.roarzone.info/player.php?stream=edge2/ptv", logo: "https://tvassets.roarzone.info/images/73.png" },
  { group: "Sports", name: "ASPORTS", stream: "https://tv.roarzone.info/player.php?stream=edge2/asports", logo: "https://tvassets.roarzone.info/images/add-sports-1.png" },
  { group: "Sports", name: "ABC Australia", stream: "https://tv.roarzone.info/player.php?stream=edge2/abc-australia", logo: "https://tvassets.roarzone.info/images/abc-australia.png" },
  { group: "Sports", name: "Sony Ten 1", stream: "https://tv.roarzone.info/player.php?stream=edge2/sony-sports-1-hd", logo: "https://tvassets.roarzone.info/images/20.png" },
  { group: "Sports", name: "Sony Ten 2", stream: "https://tv.roarzone.info/player.php?stream=edge2/sony-sports-2-hd", logo: "https://tvassets.roarzone.info/images/21.png" },
  { group: "Sports", name: "Sony Ten 3", stream: "https://tv.roarzone.info/player.php?stream=edge2/sony-sports-3-hd", logo: "https://tvassets.roarzone.info/images/22.png" },
  { group: "Sports", name: "Sony SIX", stream: "https://tv.roarzone.info/player.php?stream=edge2/sony-sports-5-hd", logo: "https://tvassets.roarzone.info/images/24.png" },
  { group: "Sports", name: "Star Sports Select 1", stream: "https://tv.roarzone.info/player.php?stream=bk/27", logo: "https://tvassets.roarzone.info/images/27.png" },
  { group: "Sports", name: "Star Sports Select 2", stream: "https://tv.roarzone.info/player.php?stream=bk/28", logo: "https://tvassets.roarzone.info/images/28.png" },
  { group: "Sports", name: "Euro Sports", stream: "https://tv.roarzone.info/player.php?stream=toffee/euro_sports_hd", logo: "https://tvassets.roarzone.info/images/euro_sports_hd.png" },
  { group: "Sports", name: "Dubai Sports", stream: "https://tv.roarzone.info/player.php?stream=bk/dubai-sports", logo: "https://tvassets.roarzone.info/images/dubai-sports.png" },
  { group: "Sports", name: "Ten Cricket", stream: "https://tv.roarzone.info/player.php?stream=toffee/ten_cricket", logo: "https://tvassets.roarzone.info/images/ten_cricket.png" },

  // --- HINDI ---
  { group: "Hindi", name: "Star Gold Select", stream: "https://tv.roarzone.info/player.php?stream=bk/72", logo: "https://tvassets.roarzone.info/images/75.png" },
  { group: "Hindi", name: "Sony TV", stream: "https://tv.roarzone.info/player.php?stream=bk/38", logo: "https://tvassets.roarzone.info/images/38.png" },
  { group: "Hindi", name: "Sony Max", stream: "https://tv.roarzone.info/player.php?stream=bk/77", logo: "https://tvassets.roarzone.info/images/sonymax.png" },
  { group: "Hindi", name: "Sony Max HD", stream: "https://tv.roarzone.info/player.php?stream=toffee/sony_max_hd", logo: "https://tvassets.roarzone.info/images/sonymaxhd.png" },
  { group: "Hindi", name: "Colors", stream: "https://tv.roarzone.info/player.php?stream=bk/68", logo: "https://tvassets.roarzone.info/images/68.png" },
  { group: "Hindi", name: "Sony Max 2", stream: "https://tv.roarzone.info/player.php?stream=toffee/sonymax_2", logo: "https://tvassets.roarzone.info/images/sonymax2.png" },
  { group: "Hindi", name: "ZEE TV", stream: "https://tv.roarzone.info/player.php?stream=bk/40", logo: "https://tvassets.roarzone.info/images/40.png" },
  { group: "Hindi", name: "Zee Cinema", stream: "https://tv.roarzone.info/player.php?stream=bk/76", logo: "https://tvassets.roarzone.info/images/76.png" },
  { group: "Hindi", name: "ZEE Bollywood", stream: "https://tv.roarzone.info/player.php?stream=toffee/zee_bollywood", logo: "https://tvassets.roarzone.info/images/94.png" },
  { group: "Hindi", name: "Zee Action", stream: "https://tv.roarzone.info/player.php?stream=toffee/zee_action", logo: "https://tvassets.roarzone.info/images/90.png" },
  { group: "Hindi", name: "Star Plus", stream: "https://tv.roarzone.info/player.php?stream=bk/67", logo: "https://tvassets.roarzone.info/images/67.png" },
  { group: "Hindi", name: "And TV HD", stream: "https://tv.roarzone.info/player.php?stream=bk/74", logo: "https://tvassets.roarzone.info/images/74.png" },
  { group: "Hindi", name: "And Pictures", stream: "https://tv.roarzone.info/player.php?stream=bk/100", logo: "https://tvassets.roarzone.info/images/100.png" },
  { group: "Hindi", name: "Hum TV", stream: "https://tv.roarzone.info/player.php?stream=toffee/hum_tv", logo: "https://tvassets.roarzone.info/images/humtv.png" },
  { group: "Hindi", name: "Zee Anmol", stream: "https://tv.roarzone.info/player.php?stream=toffee/zee_anmol", logo: "https://tvassets.roarzone.info/images/zee-anmol.png" },
  { group: "Hindi", name: "Hum Masala", stream: "https://tv.roarzone.info/player.php?stream=toffee/hum_masala", logo: "https://tvassets.roarzone.info/images/hummasala.png" },
  { group: "Hindi", name: "Hum Sitarey", stream: "https://tv.roarzone.info/player.php?stream=toffee/hum_sitaray", logo: "https://tvassets.roarzone.info/images/humsitarey.png" },
  { group: "Hindi", name: "B4U Movies", stream: "https://tv.roarzone.info/player.php?stream=toffee/b4u_movies", logo: "https://tvassets.roarzone.info/images/b4umovies.png" },

  // --- ENGLISH ---
  { group: "English", name: "Star Movies", stream: "https://tv.roarzone.info/player.php?stream=bk/starmovies", logo: "https://tvassets.roarzone.info/images/starmovies.png" },
  { group: "English", name: "Zee Cafe HD", stream: "https://tv.roarzone.info/player.php?stream=toffee/zee_cafe_hd", logo: "https://tvassets.roarzone.info/images/69.png" },
  { group: "English", name: "Sony Pix", stream: "https://tv.roarzone.info/player.php?stream=bk/41", logo: "https://tvassets.roarzone.info/images/41.png" },
  { group: "English", name: "DW NEWS", stream: "https://tv.roarzone.info/player.php?stream=bk/85", logo: "https://tvassets.roarzone.info/images/85.png" },
  { group: "English", name: "Al Jazeera", stream: "https://tv.roarzone.info/player.php?stream=bk/89", logo: "https://tvassets.roarzone.info/images/89.png" },

  // --- DOCUMENTARY ---
  { group: "Documentary", name: "Discovery HD", stream: "https://tv.roarzone.info/player.php?stream=bk/83", logo: "https://tvassets.roarzone.info/images/43.png" },
  { group: "Documentary", name: "Discovery Science", stream: "https://tv.roarzone.info/player.php?stream=toffee/discovery_science", logo: "https://tvassets.roarzone.info/images/discoveryscience.png" },
  { group: "Documentary", name: "Discovery Turbo", stream: "https://tv.roarzone.info/player.php?stream=toffee/discovery_turbo", logo: "https://tvassets.roarzone.info/images/discoveryturbo.png" },
  { group: "Documentary", name: "Discovery HD Investigation", stream: "https://tv.roarzone.info/player.php?stream=toffee/discovary_investigation_hd", logo: "https://tvassets.roarzone.info/images/discoveryhdInvestigation.png" },
  { group: "Documentary", name: "CNN", stream: "https://tv.roarzone.info/player.php?stream=toffee/cnn", logo: "https://tvassets.roarzone.info/images/cnn.png" },
  { group: "Documentary", name: "Sony BBC Earth HD", stream: "https://tv.roarzone.info/player.php?stream=bk/44", logo: "https://tvassets.roarzone.info/images/44.png" },
  { group: "Documentary", name: "Natgeo", stream: "https://tv.roarzone.info/player.php?stream=bk/35", logo: "https://tvassets.roarzone.info/images/35.png" },
  { group: "Documentary", name: "Animal Planet", stream: "https://tv.roarzone.info/player.php?stream=toffee/animal_planet_hd", logo: "https://tvassets.roarzone.info/images/animalplanet.png" },

  // --- MUSIC ---
  { group: "Music", name: "Gaan Bangla", stream: "https://tv.roarzone.info/player.php?stream=bk/58", logo: "https://tvassets.roarzone.info/images/58.png" },
  { group: "Music", name: "9xM", stream: "https://tv.roarzone.info/player.php?stream=bk/48", logo: "https://tvassets.roarzone.info/images/48.png" },
  { group: "Music", name: "ZING", stream: "https://tv.roarzone.info/player.php?stream=toffee/Zing", logo: "https://tvassets.roarzone.info/images/93.png" },
  { group: "Music", name: "B4U Music", stream: "https://tv.roarzone.info/player.php?stream=toffee/b4u_music", logo: "https://tvassets.roarzone.info/images/b4umusic.png" }
];
