const rawChannels = [
  // --- BANGLA ---
  { group: "Bangla", name: "Star Jalsha", stream: "/player.php?stream=bk/30", logo: "/images/30.png" },
  { group: "Bangla", name: "Star Jalsha Movies", stream: "/player.php?stream=bk/31", logo: "/images/31.png" },
  { group: "Bangla", name: "Zee Bangla", stream: "/player.php?stream=bk/34", logo: "/images/34.png" },
  { group: "Bangla", name: "ZEE Bangla Cinema", stream: "/player.php?stream=bk/29", logo: "/images/29.png" },
  { group: "Bangla", name: "Colors Bangla", stream: "/player.php?stream=bk/66", logo: "/images/66.png" },
  { group: "Bangla", name: "Sony Aath", stream: "/player.php?stream=bk/33", logo: "/images/33.png" },
  { group: "Bangla", name: "Jamuna TV", stream: "/player.php?stream=edge2/jamunatv", logo: "/images/13.png" },
  { group: "Bangla", name: "Nagorik TV", stream: "/player.php?stream=edge2/nagorik", logo: "/images/59.png" },
  { group: "Bangla", name: "Channel 24", stream: "/player.php?stream=edge2/channel24", logo: "/images/5.png" },
  { group: "Bangla", name: "Somoy TV", stream: "/player.php?stream=edge2/somoy", logo: "/images/17.png" },
  { group: "Bangla", name: "Ekushy TV", stream: "/player.php?stream=bk/65", logo: "/images/65.png" },
  { group: "Bangla", name: "Asian TV", stream: "/player.php?stream=edge/asian-tv", logo: "/images/62.png" },
  { group: "Bangla", name: "ATN Bangla", stream: "/player.php?stream=bk/2", logo: "/images/2.png" },
  { group: "Bangla", name: "ATN NEWS", stream: "/player.php?stream=bk/49", logo: "/images/49.png" },
  { group: "Bangla", name: "Banglavision TV", stream: "/player.php?stream=bk/3", logo: "/images/3.png" },
  { group: "Bangla", name: "Bangla TV", stream: "/player.php?stream=bk/19", logo: "/images/19.png" },
  { group: "Bangla", name: "Boishakhi TV", stream: "/player.php?stream=bk/61", logo: "/images/61.png" },
  { group: "Bangla", name: "BTV", stream: "/player.php?stream=bk/53", logo: "/images/53.png" },
  { group: "Bangla", name: "BTV World", stream: "/player.php?stream=bk/84", logo: "/images/84.png" },
  { group: "Bangla", name: "Channel 9", stream: "/player.php?stream=bk/4", logo: "/images/4.png" },
  { group: "Bangla", name: "Channel I", stream: "/player.php?stream=bk/6", logo: "/images/6.png" },
  { group: "Bangla", name: "DBC News", stream: "/player.php?stream=bk/7", logo: "/images/7.png" },
  { group: "Bangla", name: "Ekattor TV", stream: "/player.php?stream=bk/11", logo: "/images/11.png" },
  { group: "Bangla", name: "Deepto TV", stream: "/player.php?stream=bk/8", logo: "/images/8.png" },
  { group: "Bangla", name: "Desh TV", stream: "/player.php?stream=bk/9", logo: "/images/9.png" },
  { group: "Bangla", name: "Duronto TV", stream: "/player.php?stream=bk/10", logo: "/images/10.png" },
  { group: "Bangla", name: "Independent TV", stream: "/player.php?stream=bk/12", logo: "/images/12.png" },
  { group: "Bangla", name: "Maasranga", stream: "/player.php?stream=bk/51", logo: "/images/51.png" },
  { group: "Bangla", name: "Mohona TV", stream: "/player.php?stream=bk/50", logo: "/images/50.png" },
  { group: "Bangla", name: "Movie Bangla TV", stream: "/player.php?stream=bk/86", logo: "/images/86.png" },
  { group: "Bangla", name: "MY TV", stream: "/player.php?stream=bk/56", logo: "/images/56.png" },
  { group: "Bangla", name: "News24", stream: "/player.php?stream=bk/18", logo: "/images/18.png" },
  { group: "Bangla", name: "NTV", stream: "/player.php?stream=bk/54", logo: "/images/54.png" },
  { group: "Bangla", name: "RTV", stream: "/player.php?stream=bk/14", logo: "/images/14.png" },
  { group: "Bangla", name: "SA TV", stream: "/player.php?stream=bk/15", logo: "/images/15.png" },
  { group: "Bangla", name: "Sangsad TV", stream: "/player.php?stream=bk/88", logo: "/images/88.png" },
  { group: "Bangla", name: "ekhon", stream: "/player.php?stream=edge2/ekhontv", logo: "/images/ekhon-tv.jpg" },
  { group: "Bangla", name: "bijoy-tv", stream: "/player.php?stream=ext/bijoy-tv", logo: "/images/bijoy-tv.jpg" },

  // --- KIDS ---
  { group: "Kids", name: "Cartoon Network", stream: "/player.php?stream=bk/79", logo: "/images/79.png" },
  { group: "Kids", name: "Nick", stream: "/player.php?stream=bk/55", logo: "/images/55.png" },
  { group: "Kids", name: "POGO", stream: "/player.php?stream=toffee/pogo_sd", logo: "/images/pogo.png" },
  { group: "Kids", name: "Discovery Kids", stream: "/player.php?stream=toffee/discovery_kids", logo: "/images/discoverykids.png" },
  { group: "Kids", name: "Sony Yay", stream: "/player.php?stream=toffee/sonyyay", logo: "/images/sonyyay.png" },
  
  // --- SPORTS ---
  { group: "Sports", name: "T Sports", stream: "/player.php?stream=edge2/tsports", logo: "/images/102.png" },
  { group: "Sports", name: "Star Sports 1", stream: "/player.php?stream=edge2/star-sports-1-hd", logo: "/images/25.png" },
  { group: "Sports", name: "Star Sports 2", stream: "/player.php?stream=edge2/star-sports-2-hd", logo: "/images/26.png" },
  { group: "Sports", name: "Gazi TV", stream: "/player.php?stream=edge2/gazitv", logo: "/images/1.png" },
  { group: "Sports", name: "PTV spotrs", stream: "/player.php?stream=edge2/ptv", logo: "/images/73.png" },
  { group: "Sports", name: "ASPORTS", stream: "/player.php?stream=edge2/asports", logo: "/images/add-sports-1.png" },
  { group: "Sports", name: "ABC Australia", stream: "/player.php?stream=edge2/abc-australia", logo: "/images/abc-australia.png" },
  { group: "Sports", name: "Sony Ten 1", stream: "/player.php?stream=edge2/sony-sports-1-hd", logo: "/images/20.png" },
  { group: "Sports", name: "Sony Ten 2", stream: "/player.php?stream=edge2/sony-sports-2-hd", logo: "/images/21.png" },
  { group: "Sports", name: "Sony Ten 3", stream: "/player.php?stream=edge2/sony-sports-3-hd", logo: "/images/22.png" },
  { group: "Sports", name: "Sony SIX", stream: "/player.php?stream=edge2/sony-sports-5-hd", logo: "/images/24.png" },
  { group: "Sports", name: "Star Sports Select 1", stream: "/player.php?stream=bk/27", logo: "/images/27.png" },
  { group: "Sports", name: "Star Sports Select 2", stream: "/player.php?stream=bk/28", logo: "/images/28.png" },
  { group: "Sports", name: "Euro Sports", stream: "/player.php?stream=toffee/euro_sports_hd", logo: "/images/euro_sports_hd.png" },
  { group: "Sports", name: "Dubai Sports", stream: "/player.php?stream=bk/dubai-sports", logo: "/images/dubai-sports.png" },
  { group: "Sports", name: "Ten Cricket", stream: "/player.php?stream=toffee/ten_cricket", logo: "/images/ten_cricket.png" },

  // --- HINDI ---
  { group: "Hindi", name: "Star Gold Select", stream: "/player.php?stream=bk/72", logo: "/images/75.png" },
  { group: "Hindi", name: "Sony TV", stream: "/player.php?stream=bk/38", logo: "/images/38.png" },
  { group: "Hindi", name: "Sony Max", stream: "/player.php?stream=bk/77", logo: "/images/sonymax.png" },
  { group: "Hindi", name: "Sony Max HD", stream: "/player.php?stream=toffee/sony_max_hd", logo: "/images/sonymaxhd.png" },
  { group: "Hindi", name: "Colors", stream: "/player.php?stream=bk/68", logo: "/images/68.png" },
  { group: "Hindi", name: "Sony Max 2", stream: "/player.php?stream=toffee/sonymax_2", logo: "/images/sonymax2.png" },
  { group: "Hindi", name: "ZEE TV", stream: "/player.php?stream=bk/40", logo: "/images/40.png" },
  { group: "Hindi", name: "Zee Cinema", stream: "/player.php?stream=bk/76", logo: "/images/76.png" },
  { group: "Hindi", name: "ZEE Bollywood", stream: "/player.php?stream=toffee/zee_bollywood", logo: "/images/94.png" },
  { group: "Hindi", name: "Zee Action", stream: "/player.php?stream=toffee/zee_action", logo: "/images/90.png" },
  { group: "Hindi", name: "Star Plus", stream: "/player.php?stream=bk/67", logo: "/images/67.png" },
  { group: "Hindi", name: "And TV HD", stream: "/player.php?stream=bk/74", logo: "/images/74.png" },
  { group: "Hindi", name: "And Pictures", stream: "/player.php?stream=bk/100", logo: "/images/100.png" },
  { group: "Hindi", name: "Hum TV", stream: "/player.php?stream=toffee/hum_tv", logo: "/images/humtv.png" },
  { group: "Hindi", name: "Zee Anmol", stream: "/player.php?stream=toffee/zee_anmol", logo: "/images/zee-anmol.png" },
  { group: "Hindi", name: "Hum Masala", stream: "/player.php?stream=toffee/hum_masala", logo: "/images/hummasala.png" },
  { group: "Hindi", name: "Hum Sitarey", stream: "/player.php?stream=toffee/hum_sitaray", logo: "/images/humsitarey.png" },
  { group: "Hindi", name: "B4U Movies", stream: "/player.php?stream=toffee/b4u_movies", logo: "/images/b4umovies.png" },

  // --- ENGLISH ---
  { group: "English", name: "Star Movies", stream: "/player.php?stream=bk/starmovies", logo: "/images/starmovies.png" },
  { group: "English", name: "Zee Cafe HD", stream: "/player.php?stream=toffee/zee_cafe_hd", logo: "/images/69.png" },
  { group: "English", name: "Sony Pix", stream: "/player.php?stream=bk/41", logo: "/images/41.png" },
  { group: "English", name: "DW NEWS", stream: "/player.php?stream=bk/85", logo: "/images/85.png" },
  { group: "English", name: "Al Jazeera", stream: "/player.php?stream=bk/89", logo: "/images/89.png" },

  // --- DOCUMENTARY ---
  { group: "Documentary", name: "Discovery HD", stream: "/player.php?stream=bk/83", logo: "/images/43.png" },
  { group: "Documentary", name: "Discovery Science", stream: "/player.php?stream=toffee/discovery_science", logo: "/images/discoveryscience.png" },
  { group: "Documentary", name: "Discovery Turbo", stream: "/player.php?stream=toffee/discovery_turbo", logo: "/images/discoveryturbo.png" },
  { group: "Documentary", name: "Discovery HD Investigation", stream: "/player.php?stream=toffee/discovary_investigation_hd", logo: "/images/discoveryhdInvestigation.png" },
  { group: "Documentary", name: "CNN", stream: "/player.php?stream=toffee/cnn", logo: "/images/cnn.png" },
  { group: "Documentary", name: "Sony BBC Earth HD", stream: "/player.php?stream=bk/44", logo: "/images/44.png" },
  { group: "Documentary", name: "Natgeo", stream: "/player.php?stream=bk/35", logo: "/images/35.png" },
  { group: "Documentary", name: "Animal Planet", stream: "/player.php?stream=toffee/animal_planet_hd", logo: "/images/animalplanet.png" },

  // --- MUSIC ---
  { group: "Music", name: "Gaan Bangla", stream: "/player.php?stream=bk/58", logo: "/images/58.png" },
  { group: "Music", name: "9xM", stream: "/player.php?stream=bk/48", logo: "/images/48.png" },
  { group: "Music", name: "ZING", stream: "/player.php?stream=toffee/Zing", logo: "/images/93.png" },
  { group: "Music", name: "B4U Music", stream: "/player.php?stream=toffee/b4u_music", logo: "/images/b4umusic.png" }
];
